name: deploy
on:
  push:
    branches: ['master']
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn --frozen-lockfile
      - run: yarn build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          commit_message: Deploy
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          user_name: github-actions[bot]
